# Playbook to Set different power settings on Windows 11 systems
- name: Configure Windows Power Settings
  hosts: all
  gather_facts: no
  vars:
    monitor_timeout: 30         # Timeout in minutes
    brightness_level: 100       # Brightness level 
    sleep_timeout_ac: 300       # in minutes (5 hours=300)
    hibernate_enabled: false    # true = on, false = off

  tasks:
    - name: Set screen power timeout (AC mode)
      ansible.windows.win_command:
        cmd: powercfg -change -monitor-timeout-ac {{ monitor_timeout }}

    - name: Set screen full brightness
      ansible.windows.win_command:
        cmd: powershell.exe -Command "$brightness = Get-WmiObject -Namespace root/WMI -Class WmiMonitorBrightnessMethods; $brightness.WmiSetBrightness(1,{{ brightness_level }})"

    - name: Set device sleep timeout (AC mode)
      ansible.windows.win_command:
        cmd: powercfg -change -standby-timeout-ac {{ sleep_timeout_ac }}

    - name: Set device hibernate state
      ansible.windows.win_command:
        cmd: powercfg -hibernate {{ 'on' if hibernate_enabled else 'off' }}


    # To run this playbook from command line add variable value as below -
    # ansible-playbook monitor_settings.yml -e "monitor_timeout_ac=15"
